# Generated by Django 4.2.7 on 2026-06-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Fabricante",
                "verbose_name_plural": "Fabricantes",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto", models.CharField(max_length=200)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        max_length=10,
                        verbose_name="Preço",
                    ),
                ),
                ("descricao", models.TextField(default="")),
                ("estoque", models.IntegerField(default=0)),
                ("destaque", models.BooleanField(default=False)),
                ("disponivel", models.BooleanField(default=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="produtos/"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loja.categoria"
                    ),
                ),
                (
                    "fabricante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loja.fabricante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
    ]
